# Generated by Django 5.1.5 on 2025-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
                ('bubbles_caught', models.IntegerField(default=0)),
                ('bubbles_missed', models.IntegerField(default=0)),
                ('bubble_count', models.IntegerField(default=0)),
                ('jellyfish_collisions', models.IntegerField(default=0)),
                ('mountain_collisions', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('reaction_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
