# Generated by Django 5.1.5 on 2025-02-06 15:31

import django.db.models.deletion
import gameapi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0002_gamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=gameapi.models.generate_room_id, editable=False, help_text='Unique 10-digit room ID', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the room is active')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(help_text="Player's display name", max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0, help_text='Player score')),
                ('room', models.ForeignKey(help_text='The room the player is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gameapi.room')),
            ],
        ),
    ]
