# Generated by Django 5.1.5 on 2025-02-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0003_room_roomplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
