# Generated by Django 5.1.5 on 2025-02-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0005_room_leader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='leader_id',
            field=models.CharField(blank=True, help_text='Primary key of the RoomPlayer who is the leader.', max_length=300, null=True),
        ),
    ]
