# Generated by Django 5.1.5 on 2025-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='technologies',
            field=models.CharField(help_text='Comma-separated values', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tags',
            field=models.CharField(help_text='Comma-separated values', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated values', max_length=500),
        ),
    ]
